name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm install -g netlify-cli
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: netlify deploy --prod --dir=dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy to staging
        if: github.ref == 'refs/heads/develop'
        run: netlify deploy --dir=dist --site ${{ secrets.NETLIFY_STAGING_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
